== Camel application - Spring Boot example

=== Usage

    # Build the image.
    podman build --tag hello-agent-spring .

    # Run it with default properties
    podman run --publish 8080:8080 hello-agent-spring:latest

    # Run it with ENV_VAR overriding the baseUrl
    podman run --env APP_BASE_URL=http://example.com/goes/nowhere --publish 8080:8080 hello-agent-spring:latest

    # Test the app:
    curl --header "Content-Type: application/json" \
    --request POST \
    --data '{"userMessage":"Hello, who wrote Camel in Action?"}' \
    http://localhost:8080/chat

The sections below came with the example app I cloned this from.

=== Abstract

This example shows how to work with a simple Apache Camel application using Spring Boot.

=== Introduction

The example generates messages using timer trigger, writes them to standard output.

=== Camel routes

The Camel route is located in the `MyCamelRouter` class. In this class the route
starts from a timer, that triggers every 2nd second and calls a Spring Bean `MyBean`
which returns a message, that is routed to a log endpoint which writes to standard output.

=== Using Camel components

Apache Camel provides 200+ components which you can use to integrate and route messages between many systems
and data formats. To use any of these Camel components, add the component as a dependency to your project.

=== How to run

You can run this example using

    mvn spring-boot:run

=== To get health check

To show a summary of spring boot health check

----
curl -XGET -s http://localhost:8080/actuator/health
----

And you can see some info details as well

----
curl -XGET -s http://localhost:8080/actuator/info
----

See the `application.properties` to control what information to present in actuator.

=== Route coverage

This example has enabled testing with route coverage, which after running the test dumps a report, if you run:

    mvn test camel-report:route-coverage

See more details about route coverage at:
https://camel.apache.org/manual/latest/camel-report-maven-plugin.html[camel-report-maven-plugin].

=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/support.html[let us know].

We also love contributors, so
https://camel.apache.org/contributing.html[get involved] :-)

The Camel riders!



